#服务器的配置
server:
  tomcat:
    uri-encoding: UTF-8 #使用编码
  port: 80 #端口号
#  max-http-header-size: 40960


# DataSource Config
spring:
  servlet:
    multipart:
      max-file-size: 10MB # 上传文件的最大值
      max-request-size: 100MB #request的最大值
  jpa:
    show-sql: true #是否显示sql
  datasource: #数据源配置
    driver-class-name: com.mysql.cj.jdbc.Driver #驱动
    username: root
    password: test666
    type: com.alibaba.druid.pool.DruidDataSource #数据源类型
    url: jdbc:mysql://www.haomingjian.top:3309
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE #json转换的格式
  mail:
    host: smtp.163.com
    port: 465
    username: ft_ken@163.com
    password: KPLPGENXXQECBLGH
    default-encoding: UTF-8
    properties.mail.stmp.socketFactory.class: javax.net.ssl.SSLSocketFactory
    properties.mail.smtp.ssl.enable:  true
    properties.mail.debug: false


mybatis:
  type-aliases-package: app.entity #dao层实体的路径
  mapper-locations: classpath:mapper/*.xml #默认读取mapper.xml的路径
logging:
  level:
    app.dao: debug
