#服务器的配置
server:
  tomcat:
    uri-encoding: UTF-8 #使用编码
  port: 80 #端口号
#  max-http-header-size: 40960


# DataSource Config
spring:
  servlet:
    multipart:
      max-file-size: 10MB # 上传文件的最大值
      max-request-size: 100MB #request的最大值
  jpa:
    show-sql: true #是否显示sql
  datasource: #数据源配置
    driver-class-name: com.mysql.cj.jdbc.Driver #驱动
    username: root
    password: test666
    type: com.alibaba.druid.pool.DruidDataSource #数据源类型
    url: jdbc:mysql://www.94hmj.com:3308
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE #json转换的格式


mybatis:
  type-aliases-package: app.entity #dao层实体的路径
  mapper-locations: classpath:mapper/*.xml #默认读取mapper.xml的路径
logging:
  level:
    app.dao: debug
