server:
  tomcat:
    uri-encoding: UTF-8
  port: 80
#  max-http-header-size: 40960


# DataSource Config
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  jpa:
    show-sql: true
  datasource:
    #    url: jdbc:mysql://localhost:3306?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC：jdbc:mysql://www.94hmj.com:3306
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: test666
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://www.94hmj.com:3308
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE


mybatis:
  type-aliases-package: app.entity.User
  mapper-locations: classpath:mapper/*.xml